name: Store GitHub Files in Neon

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ main ]

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client jq curl

      - name: Fetch files from GitHub API and insert into Neon
        run: |
          DATABASE_URL="postgresql://admin:npg_RJV2Sn6BHwPC@ep-wild-haze-adg6n675-pooler.c-2.us-east-1.aws.neon.tech/sfolder1?channel_binding=require&sslmode=require"
          API="https://api.github.com/repos/Hupa11/pakaya/contents/session_2"

          # Make sure table exists
          psql "$DATABASE_URL" -c "CREATE TABLE IF NOT EXISTS files (
            id BIGINT PRIMARY KEY,
            filename TEXT UNIQUE,
            filecontent TEXT
          );"

          # Get list of file API URLs
          curl -s $API | jq -r '.[] | select(.type=="file") | .url' | while read file_url; do
            echo "Fetching $file_url"

            json=$(curl -s $file_url)
            filename=$(echo $json | jq -r '.name')
            content=$(echo $json | jq -r '.content' | tr -d '\n')

            # extract number from filename creds_XXXX.json
            id=$(echo $filename | sed -E 's/creds_([0-9]+)\.json/\1/')

            echo "Storing $filename (id=$id) into DB"

            psql "$DATABASE_URL" -c \
              "INSERT INTO files (id, filename, filecontent)
               VALUES ($id, '$filename', '$content')
               ON CONFLICT (id) DO UPDATE
               SET filename = EXCLUDED.filename,
                   filecontent = EXCLUDED.filecontent;"
          done
