name: Organize Files

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Organize files
        run: |

          # Move the first 300 files to session_2
          ls session | head -n 300 | xargs -I {} mv session_2/{} session_2/

          # Move the next 300 files to session_1
          ls session | head -n 600 | tail -n 300 | xargs -I {} mv session_2/{} session_1/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub pakaya"
          git add session_1 session_2
          git commit -m "Organized first 600 files into session_2 and session_1" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
